@echo off

echo ** Start Template Variables **
echo DMUSER=%DMUSER.
echo DMSERVER=%DMSERVER.
echo DMTOKEN=%DMTOKEN.

)REP DMPATH
echo DMPATH=%DMPATH.
)ENDR

echo DMSAVESTDOUT=%DMSAVESTDOUT.
echo DMSAVESTDERR=%DMSAVESTDERR.
echo DM_CURRENT_USERNAME=%DM_CURRENT_USERNAME.
echo DMREMOTEUSER=%DMREMOTEUSER.
echo DMMACHINE=%DMMACHINE.
echo DMOMDATETIME=%DMOMDATETIME.
echo DMOSPLATFORM=%DMOSPLATFORM.
echo DMFOOTPRNT=%DMFOOTPRNT.

)IFDEF DMCOMMAND
echo DMCOMMAND=%DMCOMMAND.
)ENDIF

)REP DMTARGET
echo DMTARGET=%DMTARGET.
)ENDR

)REP DMTARGET_NAME
echo DMTARGET_NAME=%DMTARGET_NAME.
)ENDR

)REP DMTARGET_RELPATH
echo DMTARGET_RELPATH=%DMTARGET_RELPATH.
)ENDR

)REP DMSOURCE
echo DMSOURCE=%DMSOURCE.
)ENDR

)REP DMSOURCE_NAME
echo DMSOURCE_NAME=%DMSOURCE_NAME.
)ENDR

)REP DMSOURCE_RELPATH
echo DMSOURCE_RELPATH=%DMSOURCE_RELPATH.
)ENDR

)REP DMINPUT
echo DMINPUT=%DMINPUT.
)ENDR

)REP DMINPUTTYPE
echo DMINPUTTYPE=%DMINPUTTYPE.
)ENDR

)REP DMINPUT_NAME
echo DMINPUT_NAME=%DMINPUT_NAME.
)ENDR

)REP DMINPUT_RELPATH
echo DMINPUT_RELPATH=%DMINPUT_RELPATH.
)ENDR

)IFDEF VS_TOOLS
echo VS_TOOLS=%VS_TOOLS.
)ENDIF

)IFDEF JAVA-HOME
echo JAVA-HOME=%JAVA-HOME.
)ENDIF

)IFDEF MAVEN-HOME
echo MAVEN-HOME=%MAVEN-HOME.
)ENDIF

echo ** End Template Variables **

echo.
echo ** Initialization **
echo.

)IFNDEF DMDIRECTORY
)SET DMDIRECTORY=_MDHEXTRACT_(+d,%(DMPATH(0)).)_
echo DMDIRECTORY=%DMDIRECTORY.
)ENDIF

)IFDEF JAVA-HOME
set java_home=%JAVA-HOME.
set path=%JAVA-HOME.\bin;%%path%%
)ENDIF

)IFDEF MAVEN-HOME
set path=%MAVEN-HOME.\bin;%%path%%
)ENDIF

echo.
echo ** Performing Build **
echo.

set RC=0

)REP DMSOURCE
call mvn -f "%DMSOURCE." package
if %%ERRORLEVEL%% neq 0 (
set RC=%%ERRORLEVEL%%
))
)ENDR

echo.
echo ** Build Complete.  RC=%%RC%% **
exit %%RC%%
